from src.server.interfaces.IResponder import IResponder
import traceback


class NerdleResponder(IResponder):
    '''
    Intention is to connect to a library of responses.
    condition them in the responder and send them down the chain for consumption by 
    engine or main.
    library should be any persistent source 
        #TODO: allow for connection to Mike DB.
    '''
    def __init__(self, library=None):
        super(NerdleResponder, self).__init__(library)

    def get_response(self, evaluation):
        '''
        gets a specific indexed response from the library based on the value generated by the
        evaluation of the guess.
        '''
        try:
            return self.library[evaluation]
        except Exception as e: 
            traceback.print_exc()

    def send_response(self):
        pass